# Generated by Django 6.1 on 2026-09-03 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapproval',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='leaveapproval',
            name='leave_request',
        ),
        migrations.RemoveConstraint(
            model_name='leavebalance',
            name='unique_employee_leave_balance_per_year',
        ),
        migrations.RemoveField(
            model_name='leavecancellation',
            name='leave_request',
        ),
        migrations.RemoveField(
            model_name='leavecancellation',
            name='requested_by',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('PAID', 'Paid Leave'), ('UNPAID', 'Unpaid Leave')], default='CASUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approver_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='LeaveApproval',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_type',
        ),
        migrations.DeleteModel(
            name='LeaveCancellation',
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
