# Generated by Django 6.1 on 2026-09-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_remove_leaveapproval_approver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='cancelled_at',
            new_name='employee_cancelled_at',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='submitted_at',
            new_name='employee_submitted_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
