# Generated by Django 6.1 on 2026-09-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_rename_cancelled_at_leaverequest_employee_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='created_at',
        ),
    ]
